import AboutUs from "./AboutUs";
import AllBlogs from "./AllBlogs";
import ConfirmSignup from "./Authentication/ConfirmSignup";
import Login from "./Authentication/Login";
import Registration from "./Authentication/Registration";
import Home from "./Home";

export * from "./AboutUs";
export * from "./AllBlogs";
export * from "./Authentication/ConfirmSignup";
export * from "./Authentication/Login";
export * from "./Authentication/Registration";
export * from "./Authentication/ResetPassword";
export * from "./Category";
export * from "./Contact";
export * from "./CookiesPolicy";
export * from "./CopyrightInfo";
export * from "./GuidLine";
export * from "./Help";
export * from "./LicenseAgreement";
// export * from "./Home";
export * from "./NotFoundPage";
export * from "./PopularImages";
export * from "./Pricing";
export * from "./Recent";
export * from "./SearchResults";
export * from "./SingleBlogPost";
export * from "./Support";
export * from "./TermsConditions";
export * from "./TrendingSearch";
export { Login, Home, AboutUs, AllBlogs, ConfirmSignup, Registration };
